// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Cw2J4axSW3SoFv21BHTT6Y-eCgZl7c0',
    appId: '1:125289527484:android:33c01a84010c421b14b8b9',
    messagingSenderId: '125289527484',
    projectId: 'mahmuza-863fc',
    storageBucket: 'mahmuza-863fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWs--XWvXx-7lXMAePCFS0dx5v5UBgzOQ',
    appId: '1:125289527484:ios:babbfa37148ecf1d14b8b9',
    messagingSenderId: '125289527484',
    projectId: 'mahmuza-863fc',
    storageBucket: 'mahmuza-863fc.appspot.com',
    iosBundleId: 'com.example.mahfuzaOverseas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWs--XWvXx-7lXMAePCFS0dx5v5UBgzOQ',
    appId: '1:125289527484:ios:babbfa37148ecf1d14b8b9',
    messagingSenderId: '125289527484',
    projectId: 'mahmuza-863fc',
    storageBucket: 'mahmuza-863fc.appspot.com',
    iosBundleId: 'com.example.mahfuzaOverseas',
  );
}
